# Render Blueprint for BookIT (Simplified)

databases:
  - name: bookit-db
    postgresMajorVersion: 16

services:
  - type: web
    name: bookit-web
    env: node
    buildCommand: "npm install && npm run build"
    startCommand: "npm start"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: bookit-db
          property: connectionString