services:
  - type: web
    name: bookit-web
    env: node
    buildCommand: npm run render-build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
    autoDeploy: true