services:
  - type: web
    name: bookit
    runtime: docker # Explicitly use Docker
    dockerfilePath: Dockerfile.prod
    env:
      NODE_ENV: production
    autoDeploy: true
    region: ohio
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: lacasita-db
          property: connectionString
    # Remove Python-specific config

databases:
  - name: lacasita-db
    plan: free
    region: ohio
    databaseName: lacasita
    user: lacasita_user