services:
  - type: web
    name: bookit-web
    env: node
    buildCommand: |
        npm install -g @wasp/cli@0.16.6
        cd wasp-core
        wasp build
    startCommand: node wasp-core/.wasp/build/server.js
    envVars:
      - key: NODE_ENV
        value: production
    autoDeploy: true