services:
  - type: web
    name: bookit-web
    env: node
    buildCommand: |
        npm install
        cd wasp-core
        npx wasp build
    startCommand: node wasp-core/.wasp/build/server.js
    envVars:
      - key: NODE_ENV
        value: production
    autoDeploy: true