services:
  - type: web
    name: bookit-web
    env: node
    plan: free
    region: oregon
    nodeVersion: "20"
    buildCommand: "npm install && npx --yes @wasp/cli@latest build"
    startCommand: "npm start"
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: WASP_TELEMETRY_ENABLED
        value: "false"