services:
  - type: web
    name: bookit
    runtime: docker
    dockerfilePath: Dockerfile.prod
    env: production
    region: ohio
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: bookit-db
          property: connectionString
    autoDeploy: true

  - type: postgres
    name: bookit-db
    region: ohio
    databaseName: bookit
    user: bookit_user