services:
  - type: web
    name: bookit
    env: node
    plan: free
    region: ohio
    buildCommand: |
      curl -sSL https://get.wasp.sh/installer.sh | sh -s -- -v 0.16.6
      export PATH=$PATH:$HOME/.local/bin
      cd wasp-core
      wasp build
      cd ..
      npm install -g serve
    startCommand: serve -s wasp-core/.wasp/build -p $PORT
    envVars:
      - key: NODE_ENV
        value: production
    autoDeploy: true

databases:
  - name: bookit-db
    region: ohio
    databaseName: bookit
    user: bookit_user