# Render Blueprint for BookIT
# This file defines both the web service and the database using a top-level 'databases' key.

databases:
  - name: bookit-db
    plan: free
    region: oregon
    postgresMajorVersion: 16

services:
  # Web Service
  - type: web
    name: bookit-web
    env: node
    plan: free
    region: oregon
    buildCommand: "npm install && npm run build"
    startCommand: "npm start"
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: WASP_TELEMETRY_ENABLED
        value: "false"
      - key: DATABASE_URL # This links the web service to the database
        fromDatabase:
          name: bookit-db
          property: connectionString